---
- name: Update and upgrade Ubuntu
  ansible.builtin.apt:
    cache_valid_time: 3600
    upgrade: true
    force_apt_get: true

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required
  changed_when: false
  ignore_errors: true

- name: Reboot the system if required
  ansible.builtin.reboot:
  when: reboot_required.stat.exists
